(function(){var h={},mt={},c={id:"485f8e597c8915da9aca0c37dca3f39f",dm:["nature.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:[],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'6D8B9F5415F21200',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var q=void 0,u=!0,v=null,w=!1;mt.cookie={};mt.cookie.set=function(a,b,f){var d;f.O&&(d=new Date,d.setTime(d.getTime()+f.O));document.cookie=a+"="+b+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(d?"; expires="+d.toGMTString():"")+(f.Fc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:v};
mt.cookie.bc=function(a,b){try{var f="Hm_ck_"+ +new Date;mt.cookie.set(f,"is-cookie-enabled",{domain:a,path:b,O:q});var d="is-cookie-enabled"===mt.cookie.get(f)?"1":"0";mt.cookie.set(f,"",{domain:a,path:b,O:-1});return d}catch(e){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ua=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.F=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.D=function(a,b){var f=w;if(a==v||!mt.lang.d(a,"Array")||b===q)return f;if(Array.prototype.indexOf)f=-1!==a.indexOf(b);else for(var d=0;d<a.length;d++)if(a[d]===b){f=u;break}return f};mt.url={};mt.url.l=function(a,b){var f=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return f?f[3]:v};
mt.url.Ac=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:v};mt.url.Hb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):v};mt.url.M=function(a){return(a=mt.url.Hb(a))?a.replace(/:\d+$/,""):a};mt.url.ra=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};
(function(){var a=mt.lang,b=mt.url;mt.g={};mt.g.zb=function(a){return document.getElementById(a)};mt.g.pa=function(a){if(!a)return v;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var d=a.split(">"),e=document.body,b=d.length-1;0<=b;b--)if(-1<d[b].indexOf("#")){var g=d[b].split("#")[1];(e=document.getElementById(g))||(e=document.getElementById(decodeURIComponent(g)));d=d.splice(b+1,d.length-(b+1));break}for(a=
0;e&&a<d.length;){var l=String(d[a]).toLowerCase();if(!("html"===l||"body"===l)){var b=0,p=d[a].match(/\[(\d+)\]/i),g=[];if(p)b=p[1]-1,l=l.split("[")[0];else if(1!==e.childNodes.length){for(var r=0,s=0,m=e.childNodes.length;s<m;s++){var x=e.childNodes[s];1===x.nodeType&&x.nodeName.toLowerCase()===l&&r++;if(1<r)return v}if(1!==r)return v}for(r=0;r<e.childNodes.length;r++)1===e.childNodes[r].nodeType&&e.childNodes[r].nodeName.toLowerCase()===l&&g.push(e.childNodes[r]);if(!g[b])return v;e=g[b]}a++}return e}catch(k){return v}};
mt.g.ra=function(a,d){var e=[],b=[];if(!a)return b;for(;a.parentNode!=v;){for(var g=0,l=0,p=a.parentNode.childNodes.length,r=0;r<p;r++){var s=a.parentNode.childNodes[r];if(s.nodeName===a.nodeName&&(g++,s===a&&(l=g),0<l&&1<g))break}if((p=""!==a.id)&&d){e.unshift("#"+encodeURIComponent(a.id));break}else p&&(p="#"+encodeURIComponent(a.id),p=0<e.length?p+">"+e.join(">"):p,b.push(p)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+l+"]":""));a=a.parentNode}b.push(e.join(">"));return b};
mt.g.sa=function(a){return(a=mt.g.ra(a,u))&&a.length?String(a[0]):""};mt.g.Kb=function(a){return mt.g.ra(a,w)};mt.g.Ab=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return v};mt.g.Db=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.g.Ib=function(a){var d={top:0,left:0};if(!a)return d;var e=mt.g.Db(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||e.scrollTop)-
(e.clientTop||0),left:d.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.g.getAttribute=function(a,d){var e=a.getAttribute&&a.getAttribute(d)||v;if(!e&&a.attributes&&a.attributes.length)for(var b=a.attributes,g=b.length,l=0;l<g;l++)b[l].nodeName===d&&(e=b[l].nodeValue);return e};mt.g.R=function(a){var d="document";a.tagName!==q&&(d=a.tagName);return d.toLowerCase()};mt.g.Ob=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.g.Q=function(f,d){var e;a.F(f)&&0===String(f).indexOf("!HMCQ!")?(e=String(f),e=b.l(document.location.href,e.substring(6,e.length))):a.F(f)||(e=mt.g.R(f),"input"===e&&d&&("button"===f.type||"submit"===f.type)?e=a.trim(f.value)||"":"input"===e&&!d&&"password"!==f.type?e=a.trim(f.value)||"":"img"===e?(e=mt.g.getAttribute,e=e(f,"alt")||e(f,"title")||e(f,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.g.Ob(f));return String(e||"").substring(0,
255)};(function(){(mt.g.ec=function(){function a(){if(!a.ca){a.ca=u;for(var d=0,b=t.length;d<b;d++)t[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var b=w,t=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,w);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!b)if(b=u,"complete"===document.readyState)a.ca=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var l=w;try{l=window.frameElement==v}catch(p){}document.documentElement.doScroll&&l&&d()}})();return function(d){a.ca?d():t.push(d)}}()).ca=w})();return mt.g})();mt.event={};
mt.event.e=function(a,b,f){a.attachEvent?a.attachEvent("on"+b,function(d){f.call(a,d)}):a.addEventListener&&a.addEventListener(b,f,w)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};
(function(){var a=mt.event;mt.f={};mt.f.Ta=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.zc=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.f.Cc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return w}};mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();
mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.gc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.Mb=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.f.Qa=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.f.C=
function(){return mt.f.Mb()+mt.f.Qa()};mt.f.ib=0;mt.f.Qb=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function b(){var a=0;window.orientation!==q&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==q)&&(a=screen.orientation.angle);mt.f.orientation=a;mt.f.ib=mt.f.Qb()}b();a.e(window,"orientationchange",b)})();return mt.f})();mt.G={};
mt.G.parse=function(a){return(new Function("return ("+a+")"))()};
mt.G.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=f[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===v)return"null";if(d instanceof Array){var e=["["],f=d.length,g,l,p;for(l=0;l<f;l++)switch(p=d[l],typeof p){case "undefined":case "function":case "unknown":break;default:g&&e.push(","),e.push(mt.G.stringify(p)),g=1}e.push("]");return e.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';g=["{"];l=mt.G.stringify;for(f in d)if(Object.prototype.hasOwnProperty.call(d,f))switch(p=
d[f],typeof p){case "undefined":case "unknown":case "function":break;default:e&&g.push(","),e=1,g.push(l(f)+":"+l(p))}g.push("}");return g.join("")}}}();mt.localStorage={};mt.localStorage.ia=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(a){return w}return u};
mt.localStorage.set=function(a,b,f){var d=new Date;d.setTime(d.getTime()+f||31536E6);try{window.localStorage?(b=d.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ia()&&(mt.localStorage.j.expires=d.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(a,b),mt.localStorage.j.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),f=a.substring(0,b)-0;if(f&&f>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ia())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(a)}catch(d){}return v};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ia())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(a),mt.localStorage.j.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(f){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):v}catch(b){return v}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.eb={};mt.eb.log=function(a,b){var f=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=f;f.onload=function(){f.onload=v;f=window[d]=v;b&&b(a)};f.src=a};mt.fb={};
mt.fb.Pb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
h.A={Bc:"http://tongji.baidu.com/hm-web/welcome/ico",$a:"hm.baidu.com/hm.gif",ob:/^(tongji|hmcdn).baidu.com$/,hb:"tongji.baidu.com",Ub:"hmmd",Vb:"hmpl",tc:"utm_medium",Tb:"hmkw",vc:"utm_term",Rb:"hmci",sc:"utm_content",Wb:"hmsr",uc:"utm_source",Sb:"hmcu",rc:"utm_campaign",N:0,J:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ya:"https:",Dc:0,xc:6E5,Ec:6E5,hc:5E3,yc:5,Na:1024,wc:1,Aa:2147483647,gb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
S:u,Ka:["a","input","button"],Ha:{id:"data-hm-id",Y:"data-hm-class",X:"data-hm-xpath",content:"data-hm-content",fa:"data-hm-tag",link:"data-hm-link"},Ja:"data-hm-enabled",Ia:"data-hm-disabled",dc:"https://hmcdn.baidu.com/static/tongji/plugins/",Za:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={B:{},e:function(a,f){this.B[a]=this.B[a]||[];this.B[a].push(f)},K:function(a,f){this.B[a]=this.B[a]||[];for(var d=this.B[a].length,e=0;e<d;e++)this.B[a][e](f)}};return h.t=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,f={Cb:function(a){var e;try{e=JSON.parse(decodeURIComponent(a[0]))}catch(b){}return e},Va:function(a,e){var f=h.c&&h.c.b&&h.c.b.u||document.location.href;b.test(a)||(f=f.replace(b,""));a=a.replace(/\/$/,"");f=f.replace(/\/$/,"");e&&(f=f.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+a.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(f)},$:function(d,e){var b=f.Cb(d);if(!a.d(b,"Undefined")){if(a.d(b,"Array")){for(var g=0;g<b.length;g++)if(f.Va(b[g],
e))return u;return w}if(a.d(b,"Object")){var g=[],l;for(l in b)b.hasOwnProperty(l)&&f.Va(l,e)&&(g=g.concat(b[l]));return g}}}};return h.na=f})();
(function(){function a(a,d){var e=document.createElement("script");e.charset="utf-8";b.d(d,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=v,d()}:e.onload=function(){d()});e.src=a;var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.cookie,b=mt.localStorage,f=mt.sessionStorage,d={getData:function(d){try{return a.get(d)||f.get(d)||b.get(d)}catch(t){}},setData:function(e,t,g){try{a.set(e,t,{domain:d.P(),path:d.aa(),O:g}),g?b.set(e,t,g):f.set(e,t)}catch(l){}},removeData:function(e){try{a.set(e,"",{domain:d.P(),path:d.aa(),O:-1}),f.remove(e),b.remove(e)}catch(t){}},T:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},da:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},P:function(){for(var a=document.location.hostname,b=0,g=c.dm.length;b<g;b++)if(d.T(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},aa:function(){for(var a=0,b=c.dm.length;a<b;a++){var g=c.dm[a];if(-1<g.indexOf("/")&&d.da(document.location.href,g))return g.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.ma=d})();
(function(){var a=mt.lang,b=mt.G,f=h.ma,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},t=["session","user"],g="Hm_up_"+c.id,l={init:function(){l.Zb()},Zb:function(){try{var e=b.parse(decodeURIComponent(f.getData(g)));a.d(e,"Object")&&(d.user=e)}catch(r){}},s:function(a){var b={};d[a]!==q&&(b=d[a]);a=this.ta();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},ta:function(){for(var a={},b,e=t.length-
1;0<=e;e--){b=d[t[e]];for(var m in b)b.hasOwnProperty(m)&&(a[m]=b[m])}return a},setProperty:function(e,g,f){var m=d[e];if(a.d(m,"Object")&&a.d(g,"Object")){for(var x in g)if(g.hasOwnProperty(x)){var k=a.h(String(x));if(f||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var n=g[x];if(n==v)delete m[k];else{if(a.d(n,"Object")||a.d(n,"Array"))n=b.stringify(n);n=a.h(String(n));l.ac(e,k,n)&&(m[k]={value:n,scope:l.Pa(e)})}}}"user"===e&&l.Ca()}},n:function(b){b!==q&&("userId"===
b&&a.d(d.user,"Object")?(delete d.user.uid_,l.Ca()):"user"===b&&a.d(d.user,"Object")?(b=d.user.uid_,d.user=b===q?{}:{uid_:b},l.Ca()):d[b]!==q&&(d[b]={}))},Ca:function(){try{f.setData(g,encodeURIComponent(b.stringify(d.user)),c.age)}catch(a){}},ac:function(a,b,e){var m=u,g=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)m=w;else{var k=g[b];g[b]={value:e,scope:l.Pa(a)};a=l.I(l.s(a));2048<encodeURIComponent(a).length&&(k!==q?g[b]=k:delete g[b],m=w)}return m},
I:function(a){var b=[],d,e;for(e in a)a.hasOwnProperty(e)&&(d=[e,a[e].value],(1===a[e].scope||2===a[e].scope)&&d.push(a[e].scope),b.push(d.join("*")));return b.join("!")},Pa:function(a){a=e[a];return a!==q?a:e.others}};return h.L=l})();
(function(){var a=mt.g,b=mt.lang,f=h.t,d=h.na,e=h.L,t=e.I;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var g={Ya:{},ga:{},init:function(){for(var a,e=d.$(c.cptrk)||[],f=0;f<e.length;f++)if(a=e[f],a.a!==q&&b.d(a.a,"Object")){a=a.a;for(var s in a)a.hasOwnProperty(s)&&(g.ga[s]=String(a[s]))}},Xa:function(){var b,d,e;for(e in g.ga)if(g.ga.hasOwnProperty(e)&&g.Ya[e]===q&&(b=g.ga[e],b=a.pa(b)))d=d===q?{}:d,d[e]=a.Q(b,w),g.Ya[e]=u;return d},va:function(){var a=g.Xa();a&&g.jc(a)},Yb:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(g.va)).observe(document.body,{childList:u,subtree:u}):window.setInterval(g.va,15E3)},jc:function(a){if(b.d(a,"Object")){e.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=t(e.s("pageview"));h.c.m();h.c.b.p=a;h.c.b.ep=d;e.n("pageview")}}};g.init();f.e("pv-b",function(){var a=g.Xa();a&&e.setProperty("pageview",a)});g.Yb();a.ec(g.va)}})();
(function(){var a=mt.lang,b=mt.g,f=h.na,d={Z:function(a,t){return function(g){var l=g.target||g.srcElement;if(l){var p=f.$(t)||[],r=l.getAttribute(a.ha);g=g.clientX+":"+g.clientY;if(r&&r===g)l.removeAttribute(a.ha);else if(0<p.length&&(l=b.Kb(l))&&l.length)if(p=l.length,r=l[l.length-1],1E4>p*r.split(">").length)for(r=0;r<p;r++)d.cb(a,l[r]);else d.cb(a,r)}}},cb:function(b,d){for(var g={},f=String(d).split(">").length,p=0;p<f;p++)g[d]="",d=d.substring(0,d.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.La)&&
b.La(g)},fc:function(a,b){return function(d){(d.target||d.srcElement).setAttribute(a.ha,d.clientX+":"+d.clientY);a&&a.o&&(b?a.o(b):a.o("#"+encodeURIComponent(this.id),d.type))}}};return h.vb=d})();
(function(){var a=mt.g,b=mt.event,f=mt.lang,d=h.A,e=h.na,t=h.vb,g=h.L,l=g.I,p={ha:"HM_ce",jb:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",t.Z(p,c.cetrk));for(var d=e.$(c.cetrk)||[],f=0,m=d.length;f<m;f++){var g=d[f],k=g.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.zb(k))&&b.e(k,"click",t.fc(p,g)))}}},La:function(a){for(var d=e.$(c.cetrk)||[],b=0;b<d.length;b++){var f=d[b],k=p.Fb(f.p,a);k&&p.o(f,k)}},Fb:function(a,d){a=String(a);if(0<a.indexOf("*")){var b=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in d)if(d.hasOwnProperty(e)&&b.test(e))return e;return v}return d.hasOwnProperty(a)?a:v},o:function(d,b){h.c.b.et=7;var e=d&&d.k||"",e=f.h(e),x={};if(d&&d.a&&f.d(d.a,"Object")){var k=d.a,n;for(n in k)if(k.hasOwnProperty(n)){var y=p.Lb(k[n]||"",b),y=y?a.Q(y,w):"";x[n]=y}}x=p.Bb(x,b||d&&d.p);x._iden=e;g.setProperty("customEvent",x);h.c.b.ep="";h.c.b.p=l(g.s("customEvent"));h.c.m();h.c.b.p="";g.n("customEvent")},
Bb:function(b,e){var m=a.pa(e),f=d.Ha;m&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(m,f.id)||a.getAttribute(m,"id")||"",b.ec_=a.getAttribute(m,f.Y)||a.getAttribute(m,"class")||"",b.ex_=a.getAttribute(m,f.X)||a.sa(m),b.en_=a.getAttribute(m,f.content)||a.Q(m,u),b.et_=a.getAttribute(m,f.fa)||a.R(m),b.el_=a.getAttribute(m,f.link)||a.getAttribute(m,"href")||""):(b.ex_=a.getAttribute(m,f.X)||a.sa(m),b.en_=a.getAttribute(m,f.content)||a.Q(m,u)));return b},Lb:function(b,d){b=String(b);d=String(d);if(0<b.indexOf("*")){var e=
/.*\[(\d+)\]$/.exec(d);b=b.replace("*",e?e[1]:"1")}return a.pa(b)}};h.t.e("pv-b",p.jb);return p})();
(function(){var a=mt.lang,b=mt.g,f=mt.event,d=mt.f,e=h.A,t=h.t,g=h.L,l=g.I,p=+new Date,r=[],s={Z:function(){return function(d){if(h.c&&h.c.S&&c.aet&&c.aet.length){var f=d.target||d.srcElement;if(f){var k=h.c.Ka,n=b.getAttribute(f,e.Ja)!=v?u:w;if(b.getAttribute(f,e.Ia)==v)if(n)s.ka(s.qa(f,d));else{var g=b.R(f);if(a.D(k,"*")||a.D(k,g))s.ka(s.qa(f,d));else for(;f.parentNode!=v;){var n=f.parentNode,g=b.R(n),z="a"===g&&a.D(k,"a")?u:w,g="button"===g&&a.D(k,"button")?u:w,A=b.getAttribute(n,e.Ja)!=v?u:w;
if(b.getAttribute(n,e.Ia)==v&&(z||g||A)){s.ka(s.qa(n,d));break}f=f.parentNode}}}}}},qa:function(f,g){var k={},n=e.Ha;k.id=b.getAttribute(f,n.id)||b.getAttribute(f,"id")||"";k.Y=b.getAttribute(f,n.Y)||b.getAttribute(f,"class")||"";k.X=b.getAttribute(f,n.X)||b.sa(f);k.content=b.getAttribute(f,n.content)||b.Q(f,u);k.fa=b.getAttribute(f,n.fa)||b.R(f);k.link=b.getAttribute(f,n.link)||b.getAttribute(f,"href")||"";k.type=g.type||"click";n=a.Ua(f.offsetTop)?f.offsetTop:0;"click"===g.type?n=d.Ta?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.Wa&&g.Wa.changedTouches)&&(n=g.Wa.changedTouches[0].pageY);k.qc=n;n=this.Eb(g);k.za=n.za||0;k.Ba=n.Ba||0;k.Ga=n.Ga||0;k.ua=n.ua||0;k.Ea=n.Ea||"b";return k},Eb:function(e){var f=e.target||e.srcElement,k;if(d.Ta){var n=Math.max(document.documentElement.scrollTop,document.body.scrollTop);k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);k=e.clientX+k;e=e.clientY+n}else k=e.pageX,
e=e.pageY;var g=n=0,z=0,A=0;if(f&&(n=f.offsetWidth||f.clientWidth,g=f.offsetHeight||f.clientHeight,A=b.Ib(f),z=A.left,A=A.top,a.d(f.getBBox,"Function")&&(g=f.getBBox(),n=g.width,g=g.height),"html"===(f.tagName||"").toLowerCase()))n=Math.max(n,f.clientWidth),g=Math.max(g,f.clientHeight);return{za:Math.round(100*((k-z)/n)),Ba:Math.round(100*((e-A)/g)),Ga:n,ua:g,Ea:("a"===(f.tagName||"").toLowerCase()?f:b.Ab(f))?"a":"b"}},ka:function(d){var b=a.h;d=[+new Date-(h.c.U!==q?h.c.U:p),b(d.id),b(d.Y),b(d.fa),
b(d.X),b(d.link),b(d.content),d.type,d.qc,d.za,d.Ba,d.Ga,d.ua,d.Ea].join("*");s.la(d);a.d(this.W(),"Function")&&this.W()()},la:function(a){var d=e.Na;a.length>d||(encodeURIComponent(r.join("!")+a).length>d&&0<r.length&&(s.o(r.join("!")),r=[]),r.push(a))},o:function(a){h.c.b.et=5;h.c.b.ep=a;g.setProperty("autoEventTracking",{view_h_:d.C()},u);h.c.b.p=l(g.s("autoEventTracking"));h.c.m();h.c.b.p="";g.setProperty("autoEventTracking",{view_h_:v},u)},W:function(){return function(){r&&r.length&&(s.o(r.join("!")),
r=[])}}};a.F(c.aet)&&""!==c.aet&&t.e("pv-b",function(){f.e(document,"click",s.Z());"ontouchend"in document&&f.e(window,"touchend",s.Z());f.e(window,"unload",s.W())});return s})();
(function(){var a=mt.lang,b=mt.event,f=mt.f,d=h.A,e=h.t,t=h.L,g=t.I,l=+new Date,p=[],r=v,s={mb:function(){a.F(c.aet)&&""!==c.aet&&setInterval(s.bb,d.hc)},bb:function(){var a=f.C();0<a-h.c.b.vl&&(h.c.b.vl=a)}},m={ub:function(){return function(){h.c&&(h.c.S&&c.aet&&c.aet.length)&&(window.clearTimeout(r),r=window.setTimeout(function(){m.lb(f.C())},150))}},lb:function(a){m.la([+new Date-(h.c.U!==q?h.c.U:l),a].join("*"))},la:function(a){if(encodeURIComponent(p.join("!")+a).length>d.Na||3<p.length)m.o(p.join("!")),
p=[];p.push(a)},o:function(a){s.bb();h.c.b.et=6;h.c.b.vh=f.Qa();h.c.b.ep=a;t.setProperty("autoEventTracking",{view_h_:f.C()},u);h.c.b.p=g(t.s("autoEventTracking"));h.c.m();h.c.b.p="";t.setProperty("autoEventTracking",{view_h_:v},u)},W:function(){return function(){p&&p.length&&(m.o(p.join("!")),p=[])}}};a.F(c.aet)&&""!==c.aet&&e.e("pv-b",function(){b.e(window,"scroll",m.ub());b.e(window,"unload",m.W());s.mb()});return m})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.oa.Jb()+","+h.oa.Gb();h.c.b.hca=c.hca;h.c.m()}}function b(){clearTimeout(z);var a;n&&(a="visible"==document[n]);y&&(a=!document[y]);l="undefined"==typeof a?u:a;if((!g||!p)&&l&&r)k=u,m=+new Date;else if(g&&p&&(!l||!r))k=w,x+=+new Date-m;g=l;p=r;z=setTimeout(b,100)}function f(a){var d=document,n="";if(a in d)n=a;else for(var b=["webkit","ms","moz","o"],e=0;e<b.length;e++){var f=b[e]+a.charAt(0).toUpperCase()+a.slice(1);
if(f in d){n=f;break}}return n}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))r="focus"==a.type||"focusin"==a.type?u:w,b()}var e=mt.event,t=h.t,g=u,l=u,p=u,r=u,s=+new Date,m=s,x=0,k=u,n=f("visibilityState"),y=f("hidden"),z;b();(function(){var a=n.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,b);e.e(window,"pageshow",b);e.e(window,"pagehide",b);"object"==typeof document.onfocusin?(e.e(document,"focusin",d),e.e(document,"focusout",d)):(e.e(window,
"focus",d),e.e(window,"blur",d))})();h.oa={Jb:function(){return+new Date-s},Gb:function(){return k?+new Date-m+x:x}};t.e("pv-b",function(){e.e(window,"unload",a())});t.e("duration-send",a());t.e("duration-done",function(){m=s=+new Date;x=0});return h.oa})();
(function(){var a=mt.lang,b=h.A,f=h.load,d={Xb:function(d){if((window._dxt===q||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var t=h.c.P();f([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(t)].join(""),d)}},pc:function(d){if(a.d(d,"String")||a.d(d,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",d])}};return h.sb=d})();
(function(){function a(a,d,b,e){if(!(a===q||d===q||e===q)){if(""===a)return[d,b,e].join("*");a=String(a).split("!");for(var f,g=w,k=0;k<a.length;k++)if(f=a[k].split("*"),String(d)===f[0]){f[1]=b;f[2]=e;a[k]=f.join("*");g=u;break}g||a.push([d,b,e].join("*"));return a.join("!")}}function b(a){for(var e in a)if({}.hasOwnProperty.call(a,e)){var f=a[e];d.d(f,"Object")||d.d(f,"Array")?b(f):a[e]=String(f)}}var f=mt.url,d=mt.lang,e=mt.G,t=mt.f,g=h.A,l=h.t,p=h.sb,r=h.load,s=h.ma,m=h.L,x=m.I,k={V:[],ea:0,xa:w,
z:{Fa:"",page:""},init:function(){k.i=0;m.init();l.e("pv-b",function(){k.tb();k.wb()});l.e("pv-d",function(){k.xb();k.z.page=""});l.e("stag-b",function(){h.c.b.api=k.i||k.ea?k.i+"_"+k.ea:"";h.c.b.ct=[decodeURIComponent(s.getData("Hm_ct_"+c.id)||""),k.z.Fa,k.z.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;k.i=0;k.ea=0})},tb:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var n=arguments[b];
d.d(n,"Array")&&(a.cmd[a.id].push(n),"_setAccount"===n[0]&&(1<n.length&&/^[0-9a-f]{31,32}$/.test(n[1]))&&(n=n[1],a.id=n,a.cmd[n]=a.cmd[n]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},wb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var d=a.cmd[c.id],b=/^_track(Event|MobConv|Order)$/,e=0,f=d.length;e<f;e++){var g=d[e];b.test(g[0])?k.V.push(g):k.Da(g)}a.cmd[c.id]={push:k.Da}},xb:function(){if(0<k.V.length)for(var a=0,d=k.V.length;a<d;a++)k.Da(k.V[a]);k.V=v},Da:function(a){var b=
a[0];if(k.hasOwnProperty(b)&&d.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(k.i|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||u===a))k.i|=2,h.c.Ra=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(k.i|=4,h.c.b.sn=h.c.Oa(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=t.C(),h.c.b.kb=0,h.c.wa?(h.c.b.nv=0,h.c.b.st=4):h.c.wa=u,k.xa||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=g.protocol+"//"+document.location.host+
a[1],h.c.b.p=x(m.s("pageview")),h.c.m(),h.c.b.p="",h.c.U=+new Date,m.n("pageview"))},_trackEvent:function(a){2<a.length&&(k.i|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.h(a[1])+"*"+d.h(a[2])+(a[3]?"*"+d.h(a[3]):"")+(a[4]?"*"+d.h(a[4]):""),h.c.b.p=x(m.ta()),h.c.m(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){k.ea++;for(var f=(h.c.b.cv||"*").split("!"),g=f.length;g<b-1;g++)f.push("*");f[b-1]=e+"*"+d.h(a[2])+"*"+d.h(a[3]);h.c.b.cv=f.join("!");
a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?s.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):s.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var e=d.h(b[1]);b=d.h(b[2]);if(e!==q&&b!==q){var f=decodeURIComponent(s.getData("Hm_ct_"+c.id)||""),f=a(f,e,1,b);s.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var e=d.h(b[1]);b=d.h(b[2]);if(e!==q&&b!==q){var f=k.z.Fa,f=a(f,e,2,b);k.z.Fa=f}}},_setPageTag:function(b){if(!(3>
b.length)){var e=d.h(b[1]);b=d.h(b[2]);if(e!==q&&b!==q){var f=k.z.page,f=a(f,e,3,b);k.z.page=f}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],d.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?g.protocol+"//"+window.location.host+a:a,k.xa=u):k.xa=w)},_trackOrder:function(a){a=a[1];d.d(a,"Object")&&(b(a),k.i|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=x(m.ta()),h.c.m(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.i|=
32,h.c.b.et=93,h.c.b.ep=a,h.c.m()},_setDataxId:function(a){a=a[1];p.Xb();p.pc(a)},_setUserId:function(a){a=a[1];if(a!==q&&(d.F(a)||d.Ua(a))){var b=m.s("user").uid_;if(!(b&&b.value===d.h(String(a)))){var b=h.c.b.p,e=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.h(String(a));h.c.m();var f={};f.uid_=a;m.setProperty("user",f,u);h.c.b.p=b;h.c.b.ep=e}}},_clearUserId:function(a){1<a.length&&u===a[1]&&m.n("userId")},_setUserProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("user",a)},_clearUserProperty:function(a){1<
a.length&&u===a[1]&&m.n("user")},_setSessionProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&m.n("session")},_setPageviewProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&m.n("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("autoEventTracking",a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&
u===a[1]&&m.n("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.Sa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.S=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.m())):l.K("duration-send");l.K("duration-done")},_require:function(a){1<a.length&&(a=a[1],g.ob.test(f.M(a))&&r(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1];a=a[2];if(d.D(g.Za,
e)&&d.d(a,"Function")&&(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]=a,b.w=b.w||[],a=b.w.slice(),e&&a.length&&a[0][1]===e))for(var f=0,k=a.length;f<k;f++){var l=a[f][2]||{};if(b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](l),b.w.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],f=a[2]||{};if(d.D(g.Za,e))if(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](f);else{b.w=b.w||[];for(var f=0,l=b.w.length;f<l;f++)if(b.w[f][1]===
e)return;b.w.push(a);k._require([v,g.dc+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.d(a,"Object")||(a={});a._iden=b;m.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=x(m.s("customEvent"));h.c.m();h.c.b.p="";m.n("customEvent")}}};k.init();h.pb=k;return h.pb})();
(function(){var a=h.t;c.spa!==q&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Sa=this.Ra=u,this.S=k.S,this.Ka=e.F(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.wa=w,this.init())}var b=mt.url,f=mt.eb,d=mt.fb,e=mt.lang,t=mt.cookie,g=mt.f,l=mt.sessionStorage,p=mt.G,r=mt.event,s=h.ma,m=h.L,x=m.I,k=h.A,n=h.load,y=h.t;a.prototype={T:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},da:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},ba:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.da(a,c.dm[d]))return u}else{var e=b.M(a);if(e&&this.T(e,c.dm[d]))return u}return w},P:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.T(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},aa:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.da(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Nb:function(){if(!document.referrer)return k.J-k.N>c.vdur?1:4;var a=w;this.ba(document.referrer)&&this.ba(document.location.href)?a=u:(a=b.M(document.referrer),a=this.T(a||"",document.location.hostname));return a?k.J-k.N>c.vdur?1:4:3},mc:function(){var a,b,d,e,f,g;k.N=s.getData("Hm_lpvt_"+c.id)||0;13===k.N.length&&(k.N=Math.round(k.N/1E3));b=this.Nb();a=4!==b?1:0;if(g=s.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.J-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.J);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.J,e="",f=1;this.$b()?(s.setData("Hm_lvt_"+c.id,g,c.age),s.setData("Hm_lpvt_"+c.id,k.J),d=t.bc(this.P(),this.aa())):this.yb();if(0===c.nv&&this.ba(document.location.href)&&(""===document.referrer||this.ba(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},$b:function(){var a=b.M(document.location.href);return!e.D("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},yb:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&s.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&s.removeData(d[0])}},lc:function(){for(var a=[],b=this.b.et,d=0,e=k.gb.length;d<e;d++){var f=k.gb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},nc:function(){this.mc();
this.b.si=c.id;this.b.sn=this.Oa();this.b.su=document.referrer;this.b.ds=g.gc;this.b.cl=g.colorDepth+"-bit";this.b.ln=String(g.language).toLowerCase();this.b.ja=g.javaEnabled?1:0;this.b.ck=g.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Pb();this.b.v="1.2.86";this.b.cv=decodeURIComponent(s.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=g.C();var a=document.location.href;this.b.cm=b.l(a,k.Ub)||"";this.b.cp=b.l(a,k.Vb)||b.l(a,k.tc)||"";this.b.cw=b.l(a,k.Tb)||
b.l(a,k.vc)||"";this.b.ci=b.l(a,k.Rb)||b.l(a,k.sc)||"";this.b.cf=b.l(a,k.Wb)||b.l(a,k.uc)||"";this.b.cu=b.l(a,k.Sb)||b.l(a,k.rc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.nc(),0===this.b.nv?this.kc():this.Ma(),h.c=this,this.rb(),this.qb(),y.K("pv-b"),this.ic()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(k.ya+"//"+k.$a+"?"+
b.join("&"))}},ic:function(){function a(){y.K("pv-d")}this.Ra?(this.wa=u,this.b.et=0,this.b.ep="",this.b.p=x(m.s("pageview")),this.b.vl=g.C(),this.m(a),this.b.p=""):a();this.U=+new Date;m.n("pageview")},m:function(a){if(this.Sa){var b=this;b.b.rnd=Math.round(Math.random()*k.Aa);b.b.r=g.orientation;b.b.ww=g.ib;y.K("stag-b");var d=k.ya+"//"+k.$a+"?"+b.lc();y.K("stag-d");b.nb(d);f.log(d,function(d){b.ab(d);e.d(a,"Function")&&a.call(b)})}},rb:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),
e=b.M(document.referrer)===k.hb?1:0,f=b.l(a,"jn"),g=/^select$/.test(f);a&&(d.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.Aa),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},qb:function(){try{if(window.postMessage&&window.self!==window.parent){var a=this;r.e(window,"message",function(d){if(b.M(d.origin)===
k.hb){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.Aa),n(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},nb:function(a){var b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+
c.id,p.stringify(b))},ab:function(a){var b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,p.stringify(b)):this.Ma()}},Ma:function(){l.remove("Hm_unsent_"+c.id)},kc:function(){var a=this,b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){f.log(k.ya+"//"+b,function(b){a.ab(b)})},
g=0;g<b.length;g++)e(b[g])},Oa:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.A,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));})();
